services:
  qemu:
    image: qemux/qemu
    container_name: marasov-archlinux
    environment:
      BOOT: "arch"
      DISK_SIZE: "32G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    volumes:
      - ./vm-files:/storage
      - .:/shared
    restart: always
    stop_grace_period: 2m
